name: lando-python
recipe: lamp
config:
  webroot: .

services:
  cli:
    type: python
    build_as_root:
      - "apt-get update -y"
      - "apt-get -y upgrade"
      - cd $LANDO_MOUNT && python -m venv my_env
      - cd $LANDO_MOUNT && pip install -r requirements.txt

tooling:
  python3:
    service: cli
    description: "Run python3: lando python3"

  python:
    service: cli
    description: "Run python3: lando python"

# lando ssh -s cli --user=root
